### ISSUE TITLE
Update uglify-es

### ISSUE THREAD

**Issue by gauntface** [ezekielchentnik/rollup-plugin-uglify-es#1]
Current dependency is 3.0.3, latest is 3.0.27

https://david-dm.org/ezekielchentnik/rollup-plugin-uglify-es

**Comment by kzc** [comment]
Hard coding `uglify-es@3.0.3` is unfortunate.

You can use the regular `rollup-plugin-uglify` with any `uglify-es` version as follows:
```js
import { rollup } from 'rollup';
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-es';

rollup({
    entry: 'main.js',
    plugins: [
        uglify({}, minify)
    ]
});
```
https://github.com/TrySound/rollup-plugin-uglify#warning

**Comment by ezekielchentnik** [comment]
Hey guys, agreed, feel free to PR

**Comment by kzc** [comment]
`rollup-plugin-uglify` is now using `uglify-es` by default.

**Comment by TrySound** [comment]
rollup-plugin-uglify again uses uglify-es
Use terser instead 
https://github.com/TrySound/rollup-plugin-terser

**Comment by ezekielchentnik** [comment]
hey guys, roll on over to: https://github.com/TrySound/rollup-plugin-terser its maintained and is latest goodness for squashing
