### ISSUE TITLE
Add minifier option

### ISSUE THREAD

**Issue by gauntface** [ezekielchentnik/rollup-plugin-uglify-es#2]
If it would be possible to add the minifier option to rollup-plugin-es, developers could use any version they want.

**Comment by TrySound** [comment]
Use `rollup-plugin-uglify` which has this option.

**Comment by ezekielchentnik** [comment]
hey guys, roll on over to: https://github.com/TrySound/rollup-plugin-terser its maintained and is latest goodness for squashing
