### ISSUE TITLE
 New dependency name: uglify-es => terser #1 

### ISSUE THREAD

**Issue by fabiosantoscode** [ezekielchentnik/rollup-plugin-uglify-es#5]
There has been development on a new fork of uglify-es, which is now called terser and has its own package!

    "terser": "^3.7.3"

Please upgrade to our new version.

**Comment by TrySound** [comment]
There is a package. I think this one should be deprecated.
https://github.com/TrySound/rollup-plugin-terser

**Comment by ezekielchentnik** [comment]
Sounds good, I'll update readme with link to: https://github.com/TrySound/rollup-plugin-terser

**Comment by ezekielchentnik** [comment]
hey guys, roll on over to: https://github.com/TrySound/rollup-plugin-terser its maintained and is latest goodness for squashing
